name: Android UI Test

on:
  push:
    branches:
      - main
  pull_request: # Add this trigger
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Install Emulator
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 28
          target: default
          arch: x86

      - name: Start Emulator
        run: |
          emulator -avd test -no-skin -no-audio -no-window &
          android-wait-for-emulator

      - name: Run UI Tests
        run: ./gradlew connectedCheck

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/androidTests/connected

