name: Android Emulator Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 19
        
    - name: Terminate Emulator
      run: /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill


    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30  # Specify the desired Android API level
        emulator-build: default  # Use a valid emulator build, not "latest"

    - name: Start Emulator
      run: emulator -avd test -no-window -no-audio -gpu off &

    - name: Wait for Emulator
      run: android-wait-for-emulator

    - name: Run Tests
      run: ./gradlew connectedAndroidTest

    - name: Terminate Emulator
      run: adb emu kill
