name: Android CI

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4.1.0

    - name: set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 19
        distribution: 'corretto'
        
    - name: Set execute permission
      run: chmod +x ./gradlew

    - name: RunAndroidTest
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with: 
        api-level: 30
        emulator-build: latest
        script: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86"

    - name: Run test
      run: ./gradlew connectedAndroidTest
      

   
