name: Android CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4.1.0

    - name: set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 19
        distribution: 'corretto'
        
    - name: Set execute permission
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Build Project
      run: ./gradlew assemble
      
    - name: Download and Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip -q commandlinetools-linux-7583922_latest.zip -d android-sdk
        export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
      working-directory: ${{ runner.workspace }}

    - name: Set up Android SDK Environment
      run: |
        echo "export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Create AVD
      run: |
        avdmanager create avd -n Pixel_4_XL_API_31 -k "system-images;android-30;google_apis;x86"

    - name: Start Android Emulator
      run: emulator -avd Pixel_4_XL_API_31 -no-window -no-audio -gpu off &

    - name: Wait for Emulator to be Ready
      run: android-wait-for-emulator

    - name: Build and run Espresso tests
      run: |
        ./gradlew assembleDebug
        ./gradlew connectedAndroidTest
