name: Android CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set execute permission
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Build Project
      run: ./gradlew assemble
