name: Android CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4.1.0

    - name: set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 19
        distribution: 'corretto'
        
    - name: Set execute permission
      run: chmod +x ./gradlew

   # - name: Run tests
    #  run: ./gradlew test

   # - name: Build Project
     # run: ./gradlew assemble
     
    - name: Run connected tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
      

   
