name: Android CI

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4.1.0

    - name: set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 19
        distribution: 'corretto'
        
    - name: Set execute permission
      run: chmod +x ./gradlew

    - name: RunAndroidTest
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with: 
        api-level: 30
        scripts: ./gradlew connectedDebugAndroidTest
      

   
